apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: wordpress
  name: wordpress
  #namespace: dev
spec:
  host: wordpress-dev.apps-crc.testing
  path: "/wordpress"
  port:
    targetPort: web
  to:
    kind: Service
    name: wordpress
    weight: 100
  wildcardPolicy: None
